import { useState } from 'react';
import { useParams } from 'react-router-dom';
import dbStore from '../utils/dbStore';

const field = 'w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-blue-600';
export default function PublicRightsRequest() {
  const params = useParams();
  const [form, setForm] = useState({ organisation_id: params.organisationId || '', principal_name: '', principal_email: '', request_type: 'Access', request_details: '' });
  const [reference, setReference] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { const result = await dbStore.submitDataPrincipalRequest(form); setReference(result); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-slate-100 px-4 py-10 text-slate-900"><div className="mx-auto max-w-xl"><header className="border-b border-slate-300 pb-5"><p className="text-xs font-semibold uppercase text-blue-700">Data Principal Rights</p><h1 className="mt-1 text-2xl font-semibold">Submit a privacy request</h1><p className="mt-2 text-sm text-slate-600">Use this form to exercise a data right or submit a privacy grievance to an organisation.</p></header>{reference ? <section className="mt-6 rounded-md border border-emerald-300 bg-emerald-50 p-5"><h2 className="font-semibold text-emerald-900">Request submitted</h2><p className="mt-2 text-sm text-emerald-800">Keep this reference for your records:</p><p className="mt-2 font-mono text-lg font-bold text-emerald-950">{reference}</p></section> : <form onSubmit={submit} className="mt-6 space-y-4 rounded-md border border-slate-300 bg-white p-5 shadow-sm">{!params.organisationId && <Label text="Organisation workspace ID"><input required pattern="[0-9a-fA-F-]{36}" value={form.organisation_id} onChange={(e) => setForm({ ...form, organisation_id: e.target.value })} className={field} /></Label>}<Label text="Full name"><input required minLength={2} maxLength={160} autoComplete="name" value={form.principal_name} onChange={(e) => setForm({ ...form, principal_name: e.target.value })} className={field} /></Label><Label text="Email"><input required type="email" autoComplete="email" value={form.principal_email} onChange={(e) => setForm({ ...form, principal_email: e.target.value })} className={field} /></Label><Label text="Request type"><select value={form.request_type} onChange={(e) => setForm({ ...form, request_type: e.target.value })} className={field}>{['Access', 'Correction', 'Erasure', 'Grievance', 'Consent Withdrawal', 'Nomination', 'Other'].map((value) => <option key={value}>{value}</option>)}</select></Label><Label text="Request details"><textarea required minLength={10} maxLength={4000} rows={6} value={form.request_details} onChange={(e) => setForm({ ...form, request_details: e.target.value })} className={field} /></Label>{error && <div role="alert" className="rounded-md border border-rose-300 bg-rose-50 px-3 py-2 text-sm text-rose-800">{error}</div>}<button disabled={loading} className="w-full rounded-md bg-blue-700 px-4 py-3 text-sm font-semibold text-white hover:bg-blue-600 disabled:opacity-50">{loading ? 'Submitting...' : 'Submit request'}</button><p className="text-xs text-slate-500">Submit only information necessary to identify and process your request. Do not include passwords, access tokens, or payment credentials.</p></form>}</div></main>;
}
function Label({ text, children }) { return <label className="block text-sm font-medium text-slate-700"><span className="mb-1 block">{text}</span>{children}</label>; }
