import { useCallback, useEffect, useMemo, useState } from 'react';
import dbStore from '../utils/dbStore';
import { resolveCurrentOrganisationId } from '../utils/currentOrganisation';

const field = 'w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white outline-none focus:border-blue-500';
const statuses = ['Submitted', 'Verification', 'In Review', 'Waiting on Principal', 'Completed', 'Rejected', 'Closed'];
export default function RightsRequestManagement() {
  const [orgId, setOrgId] = useState(null); const [requests, setRequests] = useState([]); const [members, setMembers] = useState([]); const [selectedId, setSelectedId] = useState(null); const [events, setEvents] = useState([]);
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('All'); const [type, setType] = useState('All'); const [sort, setSort] = useState('due_asc'); const [response, setResponse] = useState(''); const [note, setNote] = useState(''); const [loading, setLoading] = useState(true); const [timelineLoading, setTimelineLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const id = await resolveCurrentOrganisationId(); const [rows, memberRows] = await Promise.all([dbStore.listRightsRequests(id), dbStore.getOrgMembers(id)]); setOrgId(id); setRequests(rows); setMembers(memberRows); setSelectedId((current) => current && rows.some((row) => row.id === current) ? current : rows[0]?.id || null); } catch (err) { setError(err.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (!orgId || !selectedId) { setEvents([]); return; } setTimelineLoading(true); dbStore.listRightsRequestEvents(orgId, selectedId).then(setEvents).catch((err) => setError(err.message)).finally(() => setTimelineLoading(false)); }, [orgId, selectedId]);
  const selected = requests.find((request) => request.id === selectedId);
  useEffect(() => { setResponse(selected?.response_text || ''); }, [selectedId, selected?.response_text]);
  const visible = useMemo(() => requests.filter((request) => (!search.trim() || [request.reference_number, request.principal_name, request.principal_email].some((value) => value.toLowerCase().includes(search.toLowerCase()))) && (status === 'All' || request.status === status) && (type === 'All' || request.request_type === type)).sort((a, b) => sort === 'submitted_desc' ? new Date(b.submitted_at) - new Date(a.submitted_at) : sort === 'name_asc' ? a.principal_name.localeCompare(b.principal_name) : a.due_date.localeCompare(b.due_date)), [requests, search, status, type, sort]);
  async function update(patch, eventType, eventNote) { setSaving(true); setError(''); try { const saved = await dbStore.updateRightsRequest(orgId, selected.id, patch, eventType, eventNote); setRequests((rows) => rows.map((row) => row.id === saved.id ? saved : row)); setEvents(await dbStore.listRightsRequestEvents(orgId, selected.id)); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function addNote(event) { event.preventDefault(); setSaving(true); try { const created = await dbStore.addRightsRequestNote(orgId, selected.id, note); setEvents((rows) => [...rows, created]); setNote(''); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function remove() { if (!window.confirm(`Permanently delete ${selected.reference_number}?`)) return; setSaving(true); try { await dbStore.deleteRightsRequest(orgId, selected.id); setRequests((rows) => rows.filter((row) => row.id !== selected.id)); setSelectedId(null); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  if (loading) return <State title="Loading rights requests" detail="Fetching protected request records." />;
  return <div className="space-y-5"><header className="flex flex-col gap-3 border-b border-slate-800 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase text-cyan-400">Data Principal Operations</p><h2 className="mt-1 text-2xl font-semibold text-white">Rights Requests</h2><p className="mt-1 text-sm text-slate-400">Verify, assign, respond, and retain a complete workflow timeline.</p></div>{orgId && <a href={`/rights-request/${orgId}`} target="_blank" rel="noreferrer" className="rounded-md border border-slate-700 px-3 py-2 text-sm font-semibold text-slate-200">Open public form</a>}</header>{error && <Error message={error} retry={load} />}
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input type="search" placeholder="Search requests..." aria-label="Search requests" value={search} onChange={(e) => setSearch(e.target.value)} className={field} /><select value={status} onChange={(e) => setStatus(e.target.value)} className={field}><option>All</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select><select value={type} onChange={(e) => setType(e.target.value)} className={field}><option>All</option>{['Access', 'Correction', 'Erasure', 'Grievance', 'Consent Withdrawal', 'Nomination', 'Other'].map((value) => <option key={value}>{value}</option>)}</select><select value={sort} onChange={(e) => setSort(e.target.value)} className={field}><option value="due_asc">Due date</option><option value="submitted_desc">Newest submitted</option><option value="name_asc">Principal name</option></select></div>
    <div className="grid gap-5 xl:grid-cols-[360px_minmax(0,1fr)]"><aside className="space-y-2 border-slate-800 xl:border-r xl:pr-5">{!visible.length ? <State title="No requests" detail={requests.length ? 'No requests match the filters.' : 'Public submissions will appear here.'} /> : visible.map((request) => <button key={request.id} onClick={() => setSelectedId(request.id)} className={`w-full rounded-md border p-3 text-left ${selectedId === request.id ? 'border-cyan-500 bg-cyan-500/10' : 'border-slate-800 bg-slate-900/40'}`}><span className="flex justify-between gap-2 text-xs text-slate-500"><span>{request.reference_number}</span><span>{request.due_date}</span></span><span className="mt-1 block font-medium text-white">{request.principal_name}</span><span className="text-xs text-slate-400">{request.request_type} | {request.status}</span></button>)}</aside>
      {!selected ? <State title="Select a request" detail="Choose a request to manage its workflow." /> : <section className="min-w-0 space-y-5"><div className="border-b border-slate-800 pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-white">{selected.principal_name}</h3><p className="text-sm text-slate-400">{selected.principal_email} | {selected.reference_number}</p></div><button disabled={saving} onClick={remove} className="text-sm text-rose-400">Delete</button></div><p className="mt-3 whitespace-pre-wrap text-sm text-slate-300">{selected.request_details}</p></div>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs text-slate-400">Verification<select value={selected.verification_status} disabled={saving} onChange={(e) => update({ verification_status: e.target.value }, 'Verified', `Verification changed to ${e.target.value}.`)} className={`${field} mt-1`}>{['Pending', 'Verified', 'Failed', 'Not Required'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs text-slate-400">Assignment<select value={selected.assigned_to || ''} disabled={saving} onChange={(e) => update({ assigned_to: e.target.value || null }, 'Assigned', 'Request assignment updated.')} className={`${field} mt-1`}><option value="">Unassigned</option>{members.map((member) => <option key={member.user_id} value={member.user_id}>{member.user_profiles.full_name || member.user_profiles.email}</option>)}</select></label><label className="text-xs text-slate-400">Due date<input type="date" value={selected.due_date} disabled={saving} onChange={(e) => update({ due_date: e.target.value }, 'Status Changed', `Due date changed to ${e.target.value}.`)} className={`${field} mt-1`} /></label><label className="text-xs text-slate-400">Status<select value={selected.status} disabled={saving} onChange={(e) => update({ status: e.target.value }, 'Status Changed', `Status changed to ${e.target.value}.`)} className={`${field} mt-1`}>{statuses.map((value) => <option key={value}>{value}</option>)}</select></label></div>
        <div><label className="text-xs text-slate-400">Response<textarea rows={5} maxLength={10000} value={response} onChange={(e) => setResponse(e.target.value)} className={`${field} mt-1`} /></label><button disabled={saving || !response.trim()} onClick={() => update({ response_text: response, status: 'Completed' }, 'Response Added', 'Response recorded and request completed.')} className="mt-2 rounded-md bg-cyan-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Save response and complete</button></div>
        <div className="border-t border-slate-800 pt-4"><h3 className="font-semibold text-white">Audit timeline</h3>{timelineLoading ? <p className="mt-3 text-sm text-slate-500">Loading timeline...</p> : !events.length ? <p className="mt-3 text-sm text-slate-500">No timeline events.</p> : <ol className="mt-3 space-y-3">{events.map((item) => <li key={item.id} className="border-l-2 border-slate-700 pl-3"><p className="text-sm font-medium text-slate-200">{item.event_type}</p><p className="text-xs text-slate-400">{item.event_note || 'No note'} | {new Date(item.created_at).toLocaleString('en-IN')}</p></li>)}</ol>}<form onSubmit={addNote} className="mt-4 flex gap-2"><input required maxLength={2000} placeholder="Add an internal timeline note" value={note} onChange={(e) => setNote(e.target.value)} className={field} /><button disabled={saving} className="rounded-md border border-slate-700 px-3 text-sm font-semibold text-white">Add note</button></form></div>
      </section>}
    </div>
  </div>;
}
function State({ title, detail }) { return <div className="rounded-md border border-dashed border-slate-700 p-7 text-center"><p className="font-medium text-slate-200">{title}</p><p className="mt-1 text-sm text-slate-500">{detail}</p></div>; }
function Error({ message, retry }) { return <div role="alert" className="flex justify-between gap-3 rounded-md border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-200"><span>{message}</span><button onClick={retry} className="font-semibold text-white">Retry</button></div>; }
