import { useCallback, useEffect, useMemo, useState } from 'react';
import dbStore from '../utils/dbStore';
import { resolveCurrentOrganisationId } from '../utils/currentOrganisation';

const lifecycle = ['Intake', 'Assessing', 'Pending Approval', 'Approved', 'Reassessment Due', 'Offboarding', 'Offboarded', 'Rejected'];
const initial = { name: '', service_description: '', processor_role: 'Processor', contact_email: '', processing_countries: '', data_categories: '', lifecycle_status: 'Intake', security_score: 1, privacy_score: 1, data_sensitivity_score: 1, business_criticality_score: 1, assessment_summary: '', approval_decision: 'Pending', approval_notes: '', next_reassessment_date: '', offboarding_notes: '' };
const evidenceInitial = { evidence_type: 'DPA', document_name: '', evidence_url: '', review_status: 'Pending', expires_on: '', notes: '' };
const field = 'w-full rounded-md border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white outline-none focus:border-blue-500';
const list = (value) => value.split(',').map((item) => item.trim()).filter(Boolean);

export default function VendorRiskOperations() {
  const [orgId, setOrgId] = useState(null); const [vendors, setVendors] = useState([]); const [evidence, setEvidence] = useState([]);
  const [form, setForm] = useState(initial); const [evidenceForm, setEvidenceForm] = useState(evidenceInitial); const [editingId, setEditingId] = useState(null); const [selectedId, setSelectedId] = useState(null);
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('All'); const [sort, setSort] = useState('risk_desc'); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const id = await resolveCurrentOrganisationId(); const [vendorRows, evidenceRows] = await Promise.all([dbStore.listVendors(id), dbStore.listVendorEvidence(id)]); setOrgId(id); setVendors(vendorRows); setEvidence(evidenceRows); } catch (err) { setError(err.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const visible = useMemo(() => vendors.filter((vendor) => (!search.trim() || [vendor.name, vendor.service_description, vendor.processor_role].some((value) => value?.toLowerCase().includes(search.toLowerCase()))) && (status === 'All' || vendor.lifecycle_status === status)).sort((a, b) => sort === 'name_asc' ? a.name.localeCompare(b.name) : sort === 'reassessment_asc' ? (a.next_reassessment_date || '9999').localeCompare(b.next_reassessment_date || '9999') : b.risk_score - a.risk_score), [vendors, search, status, sort]);
  const score = (Number(form.security_score) + Number(form.privacy_score) + Number(form.data_sensitivity_score) + Number(form.business_criticality_score)) * 5;
  function reset() { setForm(initial); setEditingId(null); }
  function edit(vendor) { setEditingId(vendor.id); setSelectedId(vendor.id); setForm({ ...vendor, contact_email: vendor.contact_email || '', processing_countries: vendor.processing_countries.join(', '), data_categories: vendor.data_categories.join(', '), assessment_summary: vendor.assessment_summary || '', approval_notes: vendor.approval_notes || '', next_reassessment_date: vendor.next_reassessment_date || '', offboarding_notes: vendor.offboarding_notes || '' }); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); const payload = { ...form, processing_countries: list(form.processing_countries), data_categories: list(form.data_categories) }; try { if (editingId) { const saved = await dbStore.updateVendor(orgId, editingId, payload); setVendors((rows) => rows.map((row) => row.id === saved.id ? saved : row)); } else { const created = await dbStore.createVendor(orgId, payload); setVendors((rows) => [created, ...rows]); setSelectedId(created.id); } reset(); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function remove(vendor) { if (!window.confirm(`Delete vendor "${vendor.name}" and its evidence?`)) return; setSaving(true); try { await dbStore.deleteVendor(orgId, vendor.id); setVendors((rows) => rows.filter((row) => row.id !== vendor.id)); setEvidence((rows) => rows.filter((row) => row.vendor_id !== vendor.id)); if (selectedId === vendor.id) setSelectedId(null); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function addEvidence(event) { event.preventDefault(); if (!selectedId) { setError('Select a vendor before adding evidence.'); return; } setSaving(true); try { const created = await dbStore.createVendorEvidence(orgId, selectedId, evidenceForm); setEvidence((rows) => [created, ...rows]); setEvidenceForm(evidenceInitial); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function updateEvidence(item, review_status) { setSaving(true); try { const saved = await dbStore.updateVendorEvidence(orgId, item.id, { review_status }); setEvidence((rows) => rows.map((row) => row.id === saved.id ? saved : row)); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function deleteEvidence(item) { setSaving(true); try { await dbStore.deleteVendorEvidence(orgId, item.id); setEvidence((rows) => rows.filter((row) => row.id !== item.id)); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  if (loading) return <State title="Loading vendor register" detail="Fetching processors, assessments, and evidence." />;
  return <div className="space-y-5"><header className="border-b border-slate-800 pb-5"><p className="text-xs font-semibold uppercase text-amber-400">Third-party governance</p><h2 className="mt-1 text-2xl font-semibold text-white">Vendor and Processor Risk</h2><p className="mt-1 text-sm text-slate-400">Manage intake through assessment, approval, reassessment, and offboarding.</p></header>{error && <Error message={error} retry={load} />}
    <form onSubmit={submit} className="space-y-3 rounded-md border border-slate-800 bg-slate-900/40 p-4"><div className="flex justify-between"><h3 className="font-semibold text-white">{editingId ? 'Update vendor lifecycle' : 'Vendor intake'}</h3><div className="flex gap-3"><span className="text-sm font-semibold text-amber-300">Risk {score}/100</span>{editingId && <button type="button" onClick={reset} className="text-sm text-slate-400">Cancel</button>}</div></div>
      <div className="grid gap-3 md:grid-cols-3"><F label="Vendor name"><input required minLength={2} maxLength={160} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className={field} /></F><Sel label="Role" value={form.processor_role} values={['Processor', 'Sub-processor', 'Independent Fiduciary', 'Other']} change={(value) => setForm({ ...form, processor_role: value })} /><F label="Contact email"><input type="email" value={form.contact_email} onChange={(e) => setForm({ ...form, contact_email: e.target.value })} className={field} /></F></div>
      <F label="Service description"><textarea required minLength={3} maxLength={1000} rows={2} value={form.service_description} onChange={(e) => setForm({ ...form, service_description: e.target.value })} className={field} /></F>
      <div className="grid gap-3 md:grid-cols-2"><F label="Processing countries (comma-separated)"><input value={form.processing_countries} onChange={(e) => setForm({ ...form, processing_countries: e.target.value })} className={field} /></F><F label="Data categories (comma-separated)"><input value={form.data_categories} onChange={(e) => setForm({ ...form, data_categories: e.target.value })} className={field} /></F></div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Sel label="Lifecycle" value={form.lifecycle_status} values={lifecycle} change={(value) => setForm({ ...form, lifecycle_status: value })} />{[['Security', 'security_score'], ['Privacy', 'privacy_score'], ['Data sensitivity', 'data_sensitivity_score'], ['Criticality', 'business_criticality_score']].map(([label, key]) => <Sel key={key} label={label} value={String(form[key])} values={['1', '2', '3', '4', '5']} change={(value) => setForm({ ...form, [key]: Number(value) })} />)}</div>
      <F label="Assessment summary"><textarea maxLength={3000} rows={2} value={form.assessment_summary} onChange={(e) => setForm({ ...form, assessment_summary: e.target.value })} className={field} /></F>
      <div className="grid gap-3 md:grid-cols-3"><Sel label="Approval" value={form.approval_decision} values={['Pending', 'Approved', 'Rejected', 'Conditional']} change={(value) => setForm({ ...form, approval_decision: value })} /><F label="Next reassessment"><input type="date" value={form.next_reassessment_date} onChange={(e) => setForm({ ...form, next_reassessment_date: e.target.value })} className={field} /></F><button disabled={saving || !orgId} className="self-end rounded-md bg-amber-600 px-3 py-2 text-sm font-semibold text-white hover:bg-amber-500 disabled:opacity-50">{editingId ? 'Save vendor' : 'Create vendor'}</button></div>
      <div className="grid gap-3 md:grid-cols-2"><F label="Approval notes"><textarea maxLength={2000} rows={2} value={form.approval_notes} onChange={(e) => setForm({ ...form, approval_notes: e.target.value })} className={field} /></F><F label="Offboarding notes"><textarea maxLength={2000} rows={2} value={form.offboarding_notes} onChange={(e) => setForm({ ...form, offboarding_notes: e.target.value })} className={field} /></F></div>
    </form>
    <div className="grid gap-2 sm:grid-cols-3"><input type="search" placeholder="Search vendors..." aria-label="Search vendors" value={search} onChange={(e) => setSearch(e.target.value)} className={field} /><select aria-label="Filter lifecycle" value={status} onChange={(e) => setStatus(e.target.value)} className={field}>{['All', ...lifecycle].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Sort vendors" value={sort} onChange={(e) => setSort(e.target.value)} className={field}><option value="risk_desc">Highest risk</option><option value="name_asc">Name A-Z</option><option value="reassessment_asc">Reassessment date</option></select></div>
    {!visible.length ? <State title="No vendors" detail={vendors.length ? 'No vendors match the current search and filter.' : 'Create the first vendor intake record.'} /> : <div className="space-y-2">{visible.map((vendor) => <article key={vendor.id} className={`grid gap-3 rounded-md border p-4 lg:grid-cols-[70px_1fr_auto] lg:items-center ${selectedId === vendor.id ? 'border-amber-500' : 'border-slate-800'}`}><button onClick={() => setSelectedId(vendor.id)} className="flex h-12 w-12 items-center justify-center rounded-md bg-slate-800 font-bold text-amber-300" title="Select vendor">{vendor.risk_score}</button><div><h3 className="font-medium text-white">{vendor.name}</h3><p className="text-sm text-slate-400">{vendor.processor_role} | {vendor.lifecycle_status} | {vendor.approval_decision}</p><p className="mt-1 text-xs text-slate-500">Reassessment: {vendor.next_reassessment_date || 'Not scheduled'} | Evidence: {evidence.filter((item) => item.vendor_id === vendor.id).length}</p></div><div className="flex gap-3"><button onClick={() => edit(vendor)} className="text-sm text-blue-400">Edit</button><button disabled={saving} onClick={() => remove(vendor)} className="text-sm text-rose-400">Delete</button></div></article>)}</div>}
    <section className="grid gap-5 border-t border-slate-800 pt-5 lg:grid-cols-[340px_1fr]"><form onSubmit={addEvidence} className="space-y-3"><h3 className="font-semibold text-white">Evidence {selectedId ? `for ${vendors.find((v) => v.id === selectedId)?.name}` : ''}</h3><Sel label="Type" value={evidenceForm.evidence_type} values={['DPA', 'Security Assessment', 'Certification', 'Contract', 'Audit Report', 'Other']} change={(value) => setEvidenceForm({ ...evidenceForm, evidence_type: value })} /><F label="Document name"><input required minLength={2} value={evidenceForm.document_name} onChange={(e) => setEvidenceForm({ ...evidenceForm, document_name: e.target.value })} className={field} /></F><F label="HTTPS evidence URL"><input type="url" value={evidenceForm.evidence_url} onChange={(e) => setEvidenceForm({ ...evidenceForm, evidence_url: e.target.value })} className={field} /></F><F label="Expiry"><input type="date" value={evidenceForm.expires_on} onChange={(e) => setEvidenceForm({ ...evidenceForm, expires_on: e.target.value })} className={field} /></F><button disabled={saving || !selectedId} className="w-full rounded-md bg-blue-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Add evidence</button></form><div>{!selectedId ? <State title="Select a vendor" detail="Choose a vendor to review its evidence." /> : !evidence.some((item) => item.vendor_id === selectedId) ? <State title="No evidence" detail="Add the first assessment, agreement, or certification." /> : <div className="divide-y divide-slate-800">{evidence.filter((item) => item.vendor_id === selectedId).map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium text-white">{item.document_name}</p><p className="text-xs text-slate-500">{item.evidence_type} | Expires {item.expires_on || 'never'}</p></div><div className="flex gap-2"><select value={item.review_status} onChange={(e) => updateEvidence(item, e.target.value)} className={field}>{['Pending', 'Accepted', 'Rejected', 'Expired'].map((value) => <option key={value}>{value}</option>)}</select><button onClick={() => deleteEvidence(item)} className="text-sm text-rose-400">Delete</button></div></div>)}</div>}</div></section>
  </div>;
}
function F({ label, children }) { return <label className="block text-xs text-slate-400"><span className="mb-1 block">{label}</span>{children}</label>; }
function Sel({ label, value, values, change }) { return <F label={label}><select value={value} onChange={(e) => change(e.target.value)} className={field}>{values.map((item) => <option key={item}>{item}</option>)}</select></F>; }
function State({ title, detail }) { return <div className="rounded-md border border-dashed border-slate-700 p-7 text-center"><p className="font-medium text-slate-200">{title}</p><p className="mt-1 text-sm text-slate-500">{detail}</p></div>; }
function Error({ message, retry }) { return <div role="alert" className="flex justify-between rounded-md border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-200"><span>{message}</span><button onClick={retry} className="font-semibold text-white">Retry</button></div>; }
