/**
 * PrivSecure India — Server-Side Relational Permission Matrix (RBAC Model)
 * Stores the centralized permissions mapping for all workspace actions.
 * Enforces security validations and boundary checks.
 */

export const permissionsMatrix = {
  'Organisation Owner': [
    'organisation.view',
    'organisation.update',
    'members.view',
    'members.invite',
    'members.update',
    'members.remove',
    'settings.view',
    'settings.update',
    'audit.view',
    'inventory.view',
    'inventory.manage',
    'risk.view',
    'risk.manage',
    'consent.view',
    'consent.manage',
    'policies.view',
    'policies.manage',
    'calendar.view',
    'calendar.manage',
    'assessments.view',
    'assessments.manage',
    'requests.view',
    'requests.manage',
    'vendors.view',
    'vendors.manage',
    'incidents.view',
    'incidents.manage',
    'documents.view',
    'documents.manage',
    'reports.export',
    'billing.manage',
  ],
  'Privacy Admin': [
    'organisation.view',
    'organisation.update',
    'members.view',
    'members.invite',
    'members.update',
    'members.remove',
    'settings.view',
    'settings.update',
    'audit.view',
    'inventory.view',
    'inventory.manage',
    'risk.view',
    'risk.manage',
    'consent.view',
    'consent.manage',
    'policies.view',
    'policies.manage',
    'calendar.view',
    'calendar.manage',
    'assessments.view',
    'assessments.manage',
    'requests.view',
    'requests.manage',
    'vendors.view',
    'vendors.manage',
    'incidents.view',
    'incidents.manage',
    'documents.view',
    'documents.manage',
    'reports.export',
    'billing.manage',
  ],
  'Privacy Lead': [
    'organisation.view',
    'members.view',
    'settings.view',
    'assessments.view',
    'assessments.manage',
    'requests.view',
    'requests.manage',
    'vendors.view',
    'vendors.manage',
    'incidents.view',
    'incidents.manage',
    'documents.view',
    'documents.manage',
    'reports.export',
    'inventory.view',
    'inventory.manage',
    'risk.view',
    'risk.manage',
    'consent.view',
    'consent.manage',
    'policies.view',
    'policies.manage',
    'calendar.view',
    'calendar.manage',
  ],
  'Legal Reviewer': [
    'organisation.view',
    'settings.view',
    'requests.view',
    'requests.manage',
    'documents.view',
    'documents.manage',
    'reports.export',
    'consent.view',
    'policies.view',
    'policies.manage',
    'calendar.view',
    'calendar.manage',
  ],
  'Security Lead': [
    'organisation.view',
    'settings.view',
    'assessments.view',
    'assessments.manage',
    'vendors.view',
    'vendors.manage',
    'incidents.view',
    'incidents.manage',
    'inventory.view',
    'inventory.manage',
    'risk.view',
    'risk.manage',
    'calendar.view',
    'calendar.manage',
  ],
  'Department Owner': [
    'organisation.view',
    'assessments.view',
    'documents.view',
    'inventory.view',
    'inventory.manage',
    'risk.view',
    'calendar.view',
    'calendar.manage',
  ],
  'Auditor': [
    'organisation.view',
    'settings.view',
    'audit.view',
    'assessments.view',
    'requests.view',
    'vendors.view',
    'incidents.view',
    'documents.view',
    'reports.export',
    'inventory.view',
    'risk.view',
    'consent.view',
    'policies.view',
    'calendar.view',
  ],
  'Viewer': [
    'organisation.view',
    'settings.view',
    'assessments.view',
    'vendors.view',
    'incidents.view',
    'documents.view',
    'inventory.view',
    'risk.view',
    'consent.view',
    'policies.view',
    'calendar.view',
  ],
};

/**
 * Validates whether a specific role possesses a permission.
 */
export function hasPermission(role, permission) {
  const allowedPermissions = permissionsMatrix[role] || [];
  return allowedPermissions.includes(permission);
}
